name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: setup.py
      - name: 'Install dependencies'
        run: |
          pip install ".[dev]"

      - name: 'Checking with black'
        run: black . --check --diff --color

      - name: 'Checking with mypy'
        run: mypy src --ignore-missing-imports

      - name: 'Unit testing'
        run: pytest tests